server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:restdb}
    username: ${DB_USER:benchmark}
    password: ${DB_PASS:benchmark}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
