CREATE DATABASE restdb;
CREATE DATABASE graphqldb;
CREATE DATABASE grpcdb;

GRANT ALL PRIVILEGES ON DATABASE restdb TO benchmark;
GRANT ALL PRIVILEGES ON DATABASE graphqldb TO benchmark;
GRANT ALL PRIVILEGES ON DATABASE grpcdb TO benchmark;
